# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: kclem/crispresso2vpy3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
#      - restore_cache:
#          keys:
#            - v1-dependencies-{{ checksum "setup.py" }}
            # fallback to using the latest cache if no exact match is found
#            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            rm -rf /opt/conda/bin/CRISPRess*
            rm -rf /opt/conda/lib/python*/site-packages/CRISPResso2*
            python setup.py install

      - save_cache:
          paths:
            - /opt/conda/
          key: v1-dependencies-{{ checksum "setup.py" }}

      # run tests!
      - run:
          name: test-alive
          command: |
            CRISPResso -h

      - run:
          name: test-crispresso
          command: |
                  CRISPResso -r1 tests/FANC.Cas9.fastq -a CGGATGTTCCAATCAGTACGCAGAGAGTCGCCGTCTCCAAGGTGAAAGCGGAAGTAGGGCCTTCGCGCACCTCATGGAATCCCTTCTGCAGCACCTGGATCGCTTTTCCGAGCTTCTGGCGGTCTCAAGCACTACCTACGTCAGCACCTGGGACCCCGCCACCGTGCGCCGGGCCTTGCAGTGGGCGCGCTACCTGCGCCACATCCATCGGCGCTTTGGTCGG -g GGAATCCCTTCTGCAGCACC --debug > test-crispresso.out 2>&1
                  python tests/diff.py CRISPResso_on_FANC.Cas9 >> test-crispresso.out

      - run:
          name: test-crispresso-with-params
          command: |
                  CRISPResso -r1 tests/FANC.Cas9.fastq -a CGGATGTTCCAATCAGTACGCAGAGAGTCGCCGTCTCCAAGGTGAAAGCGGAAGTAGGGCCTTCGCGCACCTCATGGAATCCCTTCTGCAGCACCTGGATCGCTTTTCCGAGCTTCTGGCGGTCTCAAGCACTACCTACGTCAGCACCTGGGACCCCGCCACCGTGCGCCGGGCCTTGCAGTGGGCGCGCTACCTGCGCCACATCCATCGGCGCTTTGGTCGG -g GGAATCCCTTCTGCAGCACC -e CGGCCGGATGTTCCAATCAGTACGCAGAGAGTCGCCGTCTCCAAGGTGAAAGCTGAAGTAGGGCCTTCGCGCACCTCATGGAATCCCTTCTGCAGCTTTTCCGAGCTTCTGGCGGTCTCAAGCACTACCTACGTCAGCACCTGGGACCCCGCCACCGTGCGCCGGGCCTTGCAGTGGGCGCGCTACCTGCGCCACATCCATCGGCGCTTTGGTCGG -c GGGCCTTCGCGCACCTCATGGAATCCCTTCTGCAGCACCTGGATCGCTTTT --dump -qwc 20-30_45-50 -q 30 --default_min_aln_score 80 -an FANC -n params --base_edit -fg AGCCTTGCAGTGGGCGCGCTA,CCCACTGAAGGCCC --dsODN GCTAGATTTCCCAAGAAGA -gn hi -fgn dear --debug > test-crispresso-with-params.out 2>&1
                  python tests/diff.py CRISPResso_on_params >> test-crispresso-with-params.out

      - run:
          name: test-crispresso-batch
          command: |
                  cd tests && CRISPRessoBatch -bs FANC.batch -a CGGATGTTCCAATCAGTACGCAGAGAGTCGCCGTCTCCAAGGTGAAAGCGGAAGTAGGGCCTTCGCGCACCTCATGGAATCCCTTCTGCAGCACCTGGATCGCTTTTCCGAGCTTCTGGCGGTCTCAAGCACTACCTACGTCAGCACCTGGGACCCCGCCACCGTGCGCCGGGCCTTGCAGTGGGCGCGCTACCTGCGCCACATCCATCGGCGCTTTGGTCGG -g GGAATCCCTTCTGCAGCACC -p 2 --debug --base_editor --debug > ../test-crispresso-batch.out && cd ..
                  python tests/diff.py CRISPRessoBatch_on_FANC >> test-crispresso-batch.out

      - run:
          name: test-crispresso-pooled
          command: |
                  CRISPRessoPooled -r1 tests/Both.Cas9.fastq -f tests/Cas9.amplicons.txt -p 2 --keep_intermediate --min_reads_to_use_region 100 --debug > test-crispresso-pooled.out
                  python tests/diff.py CRISPRessoPooled_on_Both.Cas9 >> test-crispresso-pooled.out

      - run:
          name: test-crispresso-wgs
          command: |
                  CRISPRessoWGS -b tests/Both.Cas9.fastq.smallGenome.bam -r tests/smallGenome/smallGenome.fa -f tests/Cas9.regions.txt --debug > test-crispresso-wgs.out 2>&1
                  python tests/diff.py CRISPRessoWGS_on_Both.Cas9.fastq.smallGenome >> test-crispresso-wgs.out

      - run:
          name: test-crispresso-compare
          command: |
                  CRISPRessoCompare CRISPRessoBatch_on_FANC/CRISPResso_on_Cas9/ CRISPRessoBatch_on_FANC/CRISPResso_on_Untreated/ --debug > test-crispresso-compare.out 2>&1
                  python tests/diff.py CRISPRessoCompare_on_Cas9_VS_Untreated >> test-crispresso-compare.out

      - store_artifacts:
          path: test-crispresso.out
      - store_artifacts:
          path: test-crispresso-with-params.out
      - store_artifacts:
          path: test-crispresso-batch.out
      - store_artifacts:
          path: test-crispresso-pooled.out
      - store_artifacts:
          path: test-crispresso-wgs.out
      - store_artifacts:
          path: test-crispresso-compare.out
