name: test_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pip
  - fastp
  - numpy
  - cython
  - jinja2
  - tbb=2020.2
  - pyparsing=2.3.1
  - scipy
  - matplotlib
  - pandas
